server:
  port: 6102

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/cloud?serverTimezone=Asia/Shanghai&useSSL=false
    url: jdbc:mysql://47.96.125.238:3306/cloud?serverTimezone=Asia/Shanghai&useSSL=false
    username: lyy
    password: $Lyy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000

  redis:
#    host: 127.0.0.1
    host: 47.96.125.238
    database: 1
    password: $Lyy123456

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloud
#      username: cloud
#      password: $Lyy123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml




